import { DocPage, type DocPageData } from '../DocPage'
import {
    TextareaBasicExample,
    TextareaWithLabelExample,
    TextareaWithErrorExample,
    TextareaDisabledExample,
    TextareaWithCharCountExample,
    TextareaResizableExample,
} from './Textarea.examples'

const docData: DocPageData = {
    title: 'Textarea',
    description: 'Multi-line text input with Field wrapper for label, hint, and error.',
    importCode: "import { Textarea } from '@monority/ui/textarea'",
    usageCode: `<Textarea label="Description" rows={5} />`,
    preview: () => <TextareaBasicExample />,
    examples: [
        { title: 'With label', content: <TextareaWithLabelExample /> },
        { title: 'Error state', content: <TextareaWithErrorExample /> },
        { title: 'Disabled', content: <TextareaDisabledExample /> },
        { title: 'Character count', content: <TextareaWithCharCountExample /> },
        { title: 'Resizable', content: <TextareaResizableExample /> },
    ],
    props: [
        {
            name: 'tone',
            type: `'neutral' | 'accent' | 'danger'`,
            defaultValue: "'neutral'",
            description: 'Visual border tone.',
        },
        {
            name: 'size',
            type: `'sm' | 'md' | 'lg'`,
            defaultValue: "'md'",
            description: 'Control density.',
        },
        {
            name: 'label',
            type: 'ReactNode',
            defaultValue: '-',
            description: 'Field label rendered above the textarea.',
        },
        {
            name: 'hint',
            type: 'ReactNode',
            defaultValue: '-',
            description: 'Help text rendered below the textarea.',
        },
        {
            name: 'error',
            type: 'ReactNode',
            defaultValue: '-',
            description: 'Error message. Sets aria-invalid and replaces hint styling.',
        },
        {
            name: 'invalid',
            type: 'boolean',
            defaultValue: 'false',
            description: 'Explicit invalid state. Automatically true when error is provided.',
        },
        {
            name: 'resize',
            type: `'none' | 'vertical' | 'both'`,
            defaultValue: "'vertical'",
            description: 'Controls the CSS resize behavior.',
        },
        {
            name: 'disabled',
            type: 'boolean',
            defaultValue: 'false',
            description: 'Disables the textarea and prevents interaction.',
        },
        {
            name: 'required',
            type: 'boolean',
            defaultValue: 'false',
            description: 'Required field indicator on the label.',
        },
        {
            name: 'maxLength',
            type: 'number',
            defaultValue: '-',
            description: 'Maximum character length. Shows a live counter when set.',
        },
        {
            name: 'value',
            type: 'string',
            defaultValue: '-',
            description: 'Controlled value. When omitted, the textarea is uncontrolled and `defaultValue` sets the initial value.',
        },
        {
            name: 'defaultValue',
            type: 'string',
            defaultValue: "''",
            description: 'Uncontrolled initial value. Use instead of `value` for a controlled-less form field.',
        },
        {
            name: 'placeholder',
            type: 'string',
            defaultValue: '-',
            description: 'Native placeholder text.',
        },
    ],
    cssHooks: [
        '.mr-textarea',
        '.mr-textarea--neutral',
        '.mr-textarea--accent',
        '.mr-textarea--danger',
        '.mr-textarea--sm',
        '.mr-textarea--md',
        '.mr-textarea--lg',
        '.mr-textarea--disabled',
        '.mr-textarea--invalid',
        '.mr-textarea__counter',
        '[data-tone]',
        '[data-size]',
        '[data-disabled]',
        '[data-invalid]',
        '[data-required]',
        '[data-resize]',
        '[data-near-limit]',
    ],
    tokens: [
        '--mr-textarea-min-height',
        '--mr-fg-muted',
        '--mr-accent',
        '--mr-border-subtle',
        '--mr-border-strong',
        '--mr-bg-surface-strong',
        '--mr-bg-control',
        '--mr-shadow-focus',
        '--mr-danger',
        '--mr-warning',
        '--mr-text-xs',
        '--mr-text-sm',
        '--mr-radius-full',
        '--mr-radius-xs',
        '--mr-duration-fast',
        '--mr-ease-standard',
    ],
    a11y: [
        'Native <textarea> element with implicit form semantics.',
        'Label associated via htmlFor (auto-generated from id).',
        'aria-invalid="true" set when error is provided or invalid=true.',
        'aria-describedby connects hint and error messages to the textarea.',
        'Character counter uses aria-live="polite" for screen reader updates.',
        'Visible focus ring for keyboard navigation.',
        'Disabled state: native disabled attribute is used.',
        'Color is not the only indicator — invalid state also uses aria-invalid.',
    ],
}

export function TextareaDocs() {
    return <DocPage doc={docData} />
}
