import { defineConfig } from 'tsup'
import { resolve } from 'path'

export default defineConfig({
  entry: {
    index: 'src/index.ts',
    button: 'src/components/actions/button/index.ts',
    input: 'src/components/forms/input/index.ts',
    badge: 'src/components/feedback/badge/index.ts',
    card: 'src/components/display/card/index.ts',
    modal: 'src/components/overlays/modal/index.ts',
    alertDialog: 'src/components/overlays/alert-dialog/index.ts',
    drawer: 'src/components/overlays/drawer/index.ts',
    tooltip: 'src/components/overlays/tooltip/index.ts',
    commandPalette: 'src/components/overlays/command-palette/index.ts',
    dropdownMenu: 'src/components/overlays/dropdown-menu/index.ts',
    popover: 'src/components/overlays/popover/index.ts',
    checkbox: 'src/components/forms/checkbox/index.ts',
    combobox: 'src/components/forms/combobox/index.ts',
    switch: 'src/components/forms/switch/index.ts',
    textarea: 'src/components/forms/textarea/index.ts',
    'radio-group': 'src/components/forms/radio-group/index.ts',
    slider: 'src/components/forms/slider/index.ts',
    numberInput: 'src/components/forms/number-input/index.ts',
    passwordInput: 'src/components/forms/password-input/index.ts',
    select: 'src/components/forms/select/index.ts',
    searchInput: 'src/components/forms/search-input/index.ts',
    dataList: 'src/components/data-display/data-list/index.ts',
    dataTable: 'src/components/data-display/data-table/index.ts',
    tabs: 'src/components/navigation/tabs/index.ts',
    datePicker: 'src/components/forms/date-picker/index.ts',
    dateRangePicker: 'src/components/forms/date-range-picker/index.ts',
    formSection: 'src/components/forms/form-section/index.ts',
    fileUpload: 'src/components/forms/file-upload/index.ts',
    field: 'src/components/forms/field/index.ts',
    copyButton: 'src/components/actions/copy-button/index.ts',
    emptyState: 'src/components/feedback/empty-state/index.ts',
    asyncStateNotice: 'src/components/feedback/async-state-notice/index.ts',
    banner: 'src/components/feedback/banner/index.ts',
    callout: 'src/components/feedback/callout/index.ts',
    iconButton: 'src/components/actions/icon-button/index.ts',
    inlineAlert: 'src/components/feedback/inline-alert/index.ts',
    infiniteScroll: 'src/components/experimental/infinite-scroll/index.ts',
    progress: 'src/components/feedback/progress/index.ts',
    skeleton: 'src/components/feedback/skeleton/index.ts',
    spinner: 'src/components/feedback/spinner/index.ts',
    toast: 'src/components/feedback/toast/index.ts',
    text: 'src/components/typography/text/index.ts',
    title: 'src/components/typography/title/index.ts',
    accordion: 'src/components/display/accordion/index.ts',
    avatar: 'src/components/display/avatar/index.ts',
    metricGrid: 'src/components/display/metric-grid/index.ts',
    statCard: 'src/components/display/stat-card/index.ts',
    table: 'src/components/display/table/index.ts',
    container: 'src/components/layout/container/index.ts',
    divider: 'src/components/layout/divider/index.ts',
    grid: 'src/components/layout/grid/index.ts',
    pageHeader: 'src/components/layout/page-header/index.ts',
    section: 'src/components/layout/section/index.ts',
    stack: 'src/components/layout/stack/index.ts',
    toolbar: 'src/components/layout/toolbar/index.ts',
    breadcrumb: 'src/components/navigation/breadcrumb/index.ts',
    filterBar: 'src/components/navigation/filter-bar/index.ts',
    pagination: 'src/components/navigation/pagination/index.ts',
    sidebarLayout: 'src/components/navigation/sidebar-layout/index.ts',
    topbar: 'src/components/navigation/topbar/index.ts',
  },
  format: ['esm'],
  dts: true,
  sourcemap: true,
  clean: true,
  splitting: false,
  treeshake: true,
  minify: false,
  external: ['react', 'react-dom'],
  publicDir: 'src/styles',
  tsconfig: resolve(__dirname, 'tsconfig.json'),
})
