import { defineConfig } from 'tsup'
import { resolve } from 'node:path'

export default defineConfig({
    entry: {
        index: 'src/index.ts',
        button: 'src/components/actions/button/index.ts',
        buttonLink: 'src/components/actions/button-link/index.ts',
        input: 'src/components/forms/input/index.ts',
        badge: 'src/components/feedback/badge/index.ts',
        card: 'src/components/display/card/index.ts',
        carousel: 'src/components/display/carousel/index.ts',
        modal: 'src/components/overlays/modal/index.ts',
        alertDialog: 'src/components/overlays/alert-dialog/index.ts',
        drawer: 'src/components/overlays/drawer/index.ts',
        tooltip: 'src/components/overlays/tooltip/index.ts',
        commandPalette: 'src/components/overlays/command-palette/index.ts',
        contextMenu: 'src/components/overlays/context-menu/index.ts',
        dropdownMenu: 'src/components/overlays/dropdown-menu/index.ts',
        hoverCard: 'src/components/overlays/hover-card/index.ts',
        popover: 'src/components/overlays/popover/index.ts',
        checkbox: 'src/components/forms/checkbox/index.ts',
        calendar: 'src/components/forms/calendar/index.ts',
        collapsible: 'src/components/display/collapsible/index.ts',
        combobox: 'src/components/forms/combobox/index.ts',
        switch: 'src/components/forms/switch/index.ts',
        textarea: 'src/components/forms/textarea/index.ts',
        'radio-group': 'src/components/forms/radio-group/index.ts',
        slider: 'src/components/forms/slider/index.ts',
        numberInput: 'src/components/forms/number-input/index.ts',
        passwordInput: 'src/components/forms/password-input/index.ts',
        select: 'src/components/forms/select/index.ts',
        dataList: 'src/components/data/data-list/index.ts',
        dataTable: 'src/components/data/data-table/index.ts',
        tabs: 'src/components/navigation/tabs/index.ts',
        navigationMenu: 'src/components/navigation/navigation-menu/index.ts',
        menubar: 'src/components/navigation/menubar/index.ts',
        datePicker: 'src/components/forms/date-picker/index.ts',
        dateRangePicker: 'src/components/forms/date-range-picker/index.ts',
        formSection: 'src/components/forms/form-section/index.ts',
        fileUpload: 'src/components/forms/file-upload/index.ts',
        field: 'src/components/forms/field/index.ts',
        copyButton: 'src/components/actions/copy-button/index.ts',
        emptyState: 'src/components/feedback/empty-state/index.ts',
        asyncStateNotice: 'src/components/feedback/async-state-notice/index.ts',
        banner: 'src/components/feedback/banner/index.ts',
        callout: 'src/components/feedback/callout/index.ts',
        iconButton: 'src/components/actions/icon-button/index.ts',
        toggle: 'src/components/actions/toggle/index.ts',
        toggleGroup: 'src/components/actions/toggle-group/index.ts',
        inlineAlert: 'src/components/feedback/inline-alert/index.ts',
        infiniteScroll: 'src/components/experimental/infinite-scroll/index.ts',
        progress: 'src/components/feedback/progress/index.ts',
        skeleton: 'src/components/feedback/skeleton/index.ts',
        spinner: 'src/components/feedback/spinner/index.ts',
        toast: 'src/components/feedback/toast/index.ts',
        text: 'src/components/typography/text/index.ts',
        title: 'src/components/typography/title/index.ts',
        kbd: 'src/components/typography/kbd/index.ts',
        preCode: 'src/components/typography/pre-code/index.ts',
        accordion: 'src/components/display/accordion/index.ts',
        aspectRatio: 'src/components/layout/aspect-ratio/index.ts',
        avatar: 'src/components/display/avatar/index.ts',
        metricGrid: 'src/components/data/metric-grid/index.ts',
        statCard: 'src/components/data/stat-card/index.ts',
        table: 'src/components/data/table/index.ts',
        container: 'src/components/layout/container/index.ts',
        divider: 'src/components/layout/divider/index.ts',
        grid: 'src/components/layout/grid/index.ts',
        pageHeader: 'src/components/layout/page-header/index.ts',
        section: 'src/components/layout/section/index.ts',
        scrollArea: 'src/components/layout/scroll-area/index.ts',
        separator: 'src/components/layout/separator/index.ts',
        resizable: 'src/components/layout/resizable/index.ts',
        stack: 'src/components/layout/stack/index.ts',
        toolbar: 'src/components/layout/toolbar/index.ts',
        breadcrumb: 'src/components/navigation/breadcrumb/index.ts',
        filterBar: 'src/components/navigation/filter-bar/index.ts',
        pagination: 'src/components/navigation/pagination/index.ts',
        sidebarLayout: 'src/components/navigation/sidebar-layout/index.ts',
        topbar: 'src/components/navigation/topbar/index.ts',
        reset: 'src/styles/reset.css',
        utilities: 'src/styles/utilities.css',
        components: 'src/components/index.ts',
        hooks: 'src/hooks/index.ts',
        providers: 'src/providers/index.ts',
        primitives: 'src/primitives/index.ts',
        lib: 'src/lib/index.ts',
        'get-theme-script': 'src/providers/get-theme-script.ts',
    },
    format: ['esm'],
    dts: true,
    sourcemap: true,
    clean: true,
    // La directive « use client » est posée par script, fichier par fichier :
    // seuls ceux qui utilisent React en ont besoin (les barrels et les modules
    // purs doivent rester importables depuis un Server Component).
    onSuccess: 'node scripts/use-client.mjs',
    // true : le code partagé (FormControlContext, cn, cva, useFormControl...)
    // est extrait dans des chunks communs. Avec `false`, chaque entrée
    // embarquait sa propre copie de chaque createContext : 17 contextes
    // distincts dans le dist, donc un <Field> et un <Input> importés
    // d'entrées différentes ne partageaient plus la même instance.
    splitting: true,
    // `treeshake: true` fait réécrire chaque fichier de sortie par rollup après
    // esbuild, ce qui supprime la bannière `"use client"`. Le tree-shaking
    // esbuild suffit (mesure : +1,8 % sur dist/*.js, aucun chunk dupliqué).
    minify: false,
    external: ['react', 'react-dom'],
    // Pas de `publicDir` : il copiait `src/styles/globals.css` tel quel dans
    // dist/. Ce fichier ne fait qu'un `@import '../../../styles/src/index.css'`,
    // chemin qui sort du paquet publié et casse à l'installation. Le CSS utile
    // est déjà produit par tsup en `dist/index.css` (importé via src/index.ts),
    // avec les layers et les chemins résolus.
    tsconfig: resolve(__dirname, 'tsconfig.json'),
})
