export const datePickerMeta = {
    title: 'DatePicker',
    status: 'draft',
    package: '@monority/ui/date-picker',
    import: "import { DatePicker } from '@monority/ui'",
    category: 'forms',
    anatomy: [
        'wrapper',
        'trigger (input)',
        'icon',
        'popover (portal)',
        'header (month label + nav buttons)',
        'day-names (row)',
        'grid (day cells)',
        'hidden input (form submission)',
    ],
    accessibility: [
        'aria-expanded on trigger',
        'aria-haspopup="dialog"',
        'aria-invalid on error',
        'aria-describedby for hint/error',
        'role="dialog" on popover',
        'role="grid" on day grid',
        'role="columnheader" on day names',
        'Escape key closes popover',
        'data-* attributes for styling hooks',
    ],
}
